Add manual config for Nut and personal project

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -72,23 +72,21 @@ finished() {
     echo "done"
 }
 
-if test -f $build/Godeps
+if test -f $build/Nut.toml
 then
-    warn "Deprecated, old ./Godeps file found!"
-    warn "Please upgrade godeps (go get -u github.com/tools/godep) and"
-    warn "re-save your dependencies: godep save -r ./..."
-    name=$(<$build/Godeps jq -r .ImportPath)
-    ver=$(<$build/Godeps jq -r .GoVersion)
-elif test -f $build/Godeps/Godeps.json
-then
-    step "Checking Godeps/Godeps.json file."
-    if ! jq -r . < $build/Godeps/Godeps.json > /dev/null
-    then
-        warn "Bad Godeps/Godeps.json file"
-        exit 1
-    fi
-    name=$(<$build/Godeps/Godeps.json jq -r .ImportPath)
-    ver=$(<$build/Godeps/Godeps.json jq -r .GoVersion)
+    # TODO: Check for valid Nut.toml
+    step "Checking Nut.toml file."
+    # if ! jq -r . < $build/Godeps/Godeps.json > /dev/null
+    # then
+    #     warn "Bad Godeps/Godeps.json file"
+    #     exit 1
+    # fi
+    # TODO: remove hardcoding for name/ver
+    name="github.com/jadengore/ricetta-api"
+    ver=go1.4.2
+    # name=$(<$build/Godeps/Godeps.json jq -r .ImportPath)
+    # name=$(<$build/Godeps/Godeps.json jq -r .ImportPath)
+    # ver=$(<$build/Godeps/Godeps.json jq -r .GoVersion)
 elif test -f $build/.godir
 then
     warn "Deprecated, .godir file found!"
@@ -96,8 +94,8 @@ then
     name=$(cat $build/.godir)
     ver=go${GOVERSION:-1.5}
 else
-    warn "Godeps are required. For instructions:"
-    warn "https://devcenter.heroku.com/articles/go-support"
+    warn "Nut is required. For instructions:"
+    warn "https://github.com/jingweno/nut"
     exit 1
 fi
 
@@ -132,8 +130,8 @@ GOPATH=$build/.heroku/go export GOPATH
 PATH=$GOROOT/bin:$PATH
 
 
-if ! (test -d $build/Godeps || (which hg >/dev/null && which bzr >/dev/null))
-then
+# if ! (test -d $build/Godeps || (which hg >/dev/null && which bzr >/dev/null))
+# then
     echo
     echo "       Tired of waiting for bzr and hg?"
     echo "       Use github.com/tools/godep for faster deploys."
@@ -183,10 +181,10 @@ fi
 
 unset GIT_DIR # unset git dir or it will mess with goinstall
 cd $p
-if test -e $build/Godeps
+if test -e $build/Nut.toml
 then
-    step "Running: godep go install ${FLAGS[@]} ./..."
-    godep go install "${FLAGS[@]}" ./...
+    step "Running: nut install ${FLAGS[@]}"
+    nut install "${FLAGS[@]}"
 else
     step "Running: go get ${FLAGS[@]} ./..."
     go get "${FLAGS[@]}" ./...
